name: Release

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, windows/386, windows/amd64, darwin/386, darwin/amd64
        goos: [linux, windows, darwin]
        goarch: [386, amd64]
        exclude:
          - goarch: 386
            goos: darwin    # macOS doesn't support 32-bit
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          binary_name: "brio"
          extra_files: README.md
          goversion: "1.23.5"
          pre_command: |
            if [ "${{ matrix.goos }}" = "linux" ]; then
              sudo apt-get update && sudo apt-get install -y libx11-dev;
            fi
